version: '3.8'

services:
  dac.ac:
    container_name: dac.ac
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - net

networks:
  net:
    external: true
