---
services:
  dac.ac:
    container_name: dac.ac
    restart: always
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/dac.ac:latest
    ports:
      - "8080:8080"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dacac.rule=Host(`dac.sg`) || Host(`www.dac.sg`) || Host(`dac.ac`) || Host(`www.dac.ac`)"
      - "traefik.http.routers.dacac.entrypoints=websecure"
      - "traefik.http.routers.dacac.tls.certresolver=myresolver"
      - "traefik.http.services.dacac.loadbalancer.server.port=8080"
    environment:
      - ENVIRONMENT=production
      - CDN_URL=https://cdn.dac.sg

networks:
  proxy:
    external: true
